// Fichier : lib/products.ts
import type { Product } from './store'

// ═══════════════════════════════════════════════════════════════════
// CATALOGUE PRODUITS MURO by L&Y — Oran, Algérie
// Prix en DZD (Dinars Algériens) · 2026
// ═══════════════════════════════════════════════════════════════════
export const PRODUCTS: Product[] = [

  // ────────────────────────────────────────────────────────────────
  // 📺 SECTION 1 — MEUBLES TV SIMPLES (sur mesure, sans placo)
  // ────────────────────────────────────────────────────────────────

  {
    id:          'tv-simple-bois-noir',
    name:        'Meuble TV Bois & Noir Mat',
    nameAr:      'طاولة تلفزيون خشب وأسود مطفأ',
    category:    'tv-simple',
    emoji:       '📺',
    priceDA:     55_000,
    priceUnit:   'unité',
    dimensions:  '200 × 45 × 50 cm · sur mesure possible',
    description: 'Composition murale moderne bois naturel et noir mat. Colonnes latérales avec niches ouvertes et éclairage LED intégré. Fabrication sur mesure Oran.',
    image:       '/images/tv/meuble-tv-moderne-bois-noir.jpg',
    model3d:     '/models/tv-stand-180.glb',
    inStock:     true,
  },
  {
    id:          'tv-simple-flottant-chene',
    name:        'Meuble TV Flottant Chêne Vieilli',
    nameAr:      'طاولة تلفزيون عائمة بلوط قديم',
    category:    'tv-simple',
    emoji:       '🪵',
    priceDA:     48_000,
    priceUnit:   'unité',
    dimensions:  '180 × 30 × 25 cm · L personnalisable',
    description: 'Meuble TV suspendu contemporain finition chêne vieilli. Éclairage LED sous caisson. Portes à push-open. MDF hydrofuge, montage mural solide.',
    image:       '/images/tv/meuble-tv-chene-vieilli-led.webp',
    model3d:     '/models/tv-floating.glb',
    inStock:     true,
  },
  {
    id:          'tv-simple-flottant-beige',
    name:        'Meuble TV Flottant Luxe Beige',
    nameAr:      'طاولة تلفزيون فاخرة بيج عائمة',
    category:    'tv-simple',
    emoji:       '🏮',
    priceDA:     72_000,
    priceUnit:   'unité',
    dimensions:  '250 × 35 × 30 cm · extensible à 300cm',
    description: 'Meuble TV panoramique laqué beige satiné. Façade striée centrale dorée. Rangements à tiroirs silencieux Blum. Style minimaliste luxe, fabrication locale.',
    image:       '/images/tv/meuble-tv-flottant-beige-luxe.webp',
    model3d:     '/models/tv-floating.glb',
    inStock:     true,
  },
  {
    id:          'tv-simple-bibliotheque',
    name:        'Bibliothèque TV Noir & Bois',
    nameAr:      'مكتبة تلفزيون أسود وخشب',
    category:    'tv-simple',
    emoji:       '📚',
    priceDA:     95_000,
    priceUnit:   'unité',
    dimensions:  '220 × 220 × 40 cm · hauteur plafond',
    description: 'Composition bibliothèque mur entier noir mat avec tablettes bois massif. Lambris shiplap vertical intégré. LED indirect. Colonne rangement haute avec portes.',
    image:       '/images/tv/meuble-tv-bibliotheque-noir-bois.jpg',
    model3d:     '/models/bookcase.glb',
    inStock:     true,
  },

  // ────────────────────────────────────────────────────────────────
  // 🏛️ SECTION 2 — MEUBLES TV AVEC DÉCORATION PLACOPLATRE
  // ────────────────────────────────────────────────────────────────

  {
    id:          'tv-deco-mural-anthracite',
    name:        'Mur TV Anthracite + Shiplap LED',
    nameAr:      'جدار تلفزيون أنثراسيت مع LED',
    category:    'tv-deco',
    emoji:       '🎬',
    priceDA:     185_000,
    priceUnit:   'forfait',
    dimensions:  'Mur complet 300–400 cm · pose incluse',
    description: 'Mur TV mural haut de gamme : parement BA13 anthracite, lambris shiplap bois vertical avec LED indirect doré, meuble bas laqué gris. Niches flottantes éclairées. Câbles TV encastrés. Pose complète incluse.',
    image:       '/images/tv/meuble-tv-mural-anthracite-shiplap.jpg',
    model3d:     '/models/tv-stand-180.glb',
    inStock:     true,
  },
  {
    id:          'tv-deco-placo-niches-led',
    name:        'Mur TV Placo Niches & LED',
    nameAr:      'جدار تلفزيون جبس مع أضواء LED',
    category:    'tv-deco',
    emoji:       '💡',
    priceDA:     145_000,
    priceUnit:   'forfait',
    dimensions:  'Mur 280–350 cm · sur mesure',
    description: 'Composition BA13 avec cadre TV encastré éclairé en LED chaud, niches latérales décoratives sur mesure, meuble flottant bois + blanc. Finition peinture satin incluse. Câblage TV propre.',
    image:       '/images/tv/meuble-tv-placo-led-niches.jpg',
    model3d:     '/models/tv-stand-120.glb',
    inStock:     true,
  },
  {
    id:          'tv-deco-marbre-bibliotheque',
    name:        'Mur TV Marbre & Bibliothèque LED',
    nameAr:      'جدار رخام مع مكتبة LED',
    category:    'tv-deco',
    emoji:       '🪨',
    priceDA:     220_000,
    priceUnit:   'forfait',
    dimensions:  'Mur 350–450 cm · grande bibliothèque',
    description: 'Composition prestige : panneau mural faux marbre blanc Carrare, bibliothèque sur mesure bois naturel avec éclairage LED à chaque tablette, meuble bas bois. Rendu 5 étoiles, fabrication et pose Oran.',
    image:       '/images/tv/meuble-tv-marbre-bibliotheque.webp',
    model3d:     '/models/bookcase.glb',
    inStock:     true,
  },

  // ────────────────────────────────────────────────────────────────
  // ANCIENS PRODUITS TV (conservés pour compatibilité)
  // ────────────────────────────────────────────────────────────────
  {
    id:          'tv-led-120',
    name:        'Meuble TV LED 120cm',
    nameAr:      'طاولة تلفزيون LED',
    category:    'tv',
    emoji:       '📺',
    priceDA:     45_000,
    priceUnit:   'unité',
    dimensions:  '120 × 50 × 45 cm',
    description: 'Meuble TV moderne avec éclairage LED intégré. Finition laque blanc mat ou chêne naturel. Fabrication locale Oran.',
    model3d:     '/models/tv-stand-120.glb',
    inStock:     true,
  },
  {
    id:          'tv-led-180',
    name:        'Meuble TV LED 180cm',
    nameAr:      'طاولة تلفزيون LED كبيرة',
    category:    'tv',
    emoji:       '🖥️',
    priceDA:     65_000,
    priceUnit:   'unité',
    dimensions:  '180 × 55 × 45 cm',
    description: 'Grand meuble TV avec colonnes latérales et niches de rangement. LED RGB inclus.',
    model3d:     '/models/tv-stand-180.glb',
    inStock:     true,
  },
  {
    id:          'tv-flottant',
    name:        'Meuble TV Flottant',
    nameAr:      'طاولة تلفزيون عائمة',
    category:    'tv',
    emoji:       '🔲',
    priceDA:     38_000,
    priceUnit:   'unité',
    dimensions:  '150 × 30 × 25 cm',
    description: 'Meuble TV suspendu au mur. Minimaliste, économise de la place. MDF hydrofuge.',
    model3d:     '/models/tv-floating.glb',
    inStock:     true,
  },
  {
    id:          'bibliotheque',
    name:        'Bibliothèque Modulable',
    nameAr:      'مكتبة معيارية',
    category:    'tv',
    emoji:       '📚',
    priceDA:     95_000,
    priceUnit:   'unité',
    dimensions:  '200 × 200 × 35 cm',
    description: 'Bibliothèque mur entier avec éclairage LED. Sur mesure disponible.',
    model3d:     '/models/bookcase.glb',
    inStock:     true,
  },

  // ── REVÊTEMENTS MURAUX ───────────────────────────────────────────
  {
    id:          'faux-marbre-blanc',
    name:        'Faux Marbre Blanc Carrare',
    nameAr:      'رخام أبيض اصطناعي',
    category:    'murs',
    emoji:       '🪨',
    priceDA:     3_500,
    priceUnit:   'm²',
    dimensions:  'Panel 60 × 60 cm · ép. 3mm',
    description: 'Revêtement mural effet marbre blanc veinage gris. Résistant humidité. Idéal salle de bain, cuisine, salon.',
    model3d:     '/models/marble-panel.glb',
    inStock:     true,
  },
  {
    id:          'shiplap-chene',
    name:        'Shiplap Chêne Naturel',
    nameAr:      'ألواح خشبية بلوط طبيعي',
    category:    'murs',
    emoji:       '🪵',
    priceDA:     2_800,
    priceUnit:   'm²',
    dimensions:  'Lame 200 × 18 cm · ép. 12mm',
    description: 'Bardage mural horizontal effet bois chêne. Finition naturelle ou teinté. Pose clipsée.',
    model3d:     '/models/shiplap.glb',
    inStock:     true,
  },
  {
    id:          'ba13-placo',
    name:        'Cloison BA13 Placo',
    nameAr:      'جدار جبسي',
    category:    'murs',
    emoji:       '🏗️',
    priceDA:     1_200,
    priceUnit:   'm²',
    dimensions:  'Plaque 250 × 120 cm · ép. 13mm',
    description: 'Cloison sèche BA13 standard. Pose sur ossature métallique. Inclut joint et entoilage.',
    inStock:     true,
  },
  {
    id:          'panneau-3d-mdf',
    name:        'Panneau 3D MDF Géométrique',
    nameAr:      'لوح ثلاثي الأبعاد',
    category:    'murs',
    emoji:       '🎨',
    priceDA:     8_500,
    priceUnit:   'unité',
    dimensions:  '60 × 60 cm · ép. 18mm',
    description: 'Panneau mural 3D en MDF, motifs géométriques. Peindre selon votre couleur.',
    model3d:     '/models/panel-3d.glb',
    inStock:     true,
  },

  // ── ÉCLAIRAGE ────────────────────────────────────────────────────
  {
    id:          'led-rgb-3m',
    name:        'Ruban LED RGB 3m',
    nameAr:      'شريط LED RGB',
    category:    'lumiere',
    emoji:       '💡',
    priceDA:     6_500,
    priceUnit:   'unité',
    dimensions:  '300 × 8 mm',
    description: 'Ruban LED RGB avec télécommande et app WiFi. 16 millions de couleurs. Adhesif double face.',
    inStock:     true,
  },
  {
    id:          'applique-laiton',
    name:        'Applique Murale Laiton',
    nameAr:      'مصباح جداري نحاسي',
    category:    'lumiere',
    emoji:       '🔆',
    priceDA:     18_000,
    priceUnit:   'unité',
    dimensions:  '20 × 35 cm',
    description: 'Applique murale style industriel, finition laiton brossé. Ampoule E27 incluse.',
    inStock:     true,
  },
  {
    id:          'spot-encastre',
    name:        'Spot Encastré LED',
    nameAr:      'مصباح LED مدمج',
    category:    'lumiere',
    emoji:       '🌟',
    priceDA:     4_200,
    priceUnit:   'unité',
    dimensions:  'Ø9 cm',
    description: 'Spot encastré LED 7W. Blanc chaud 3000K. Lot de 6 disponible.',
    inStock:     true,
  },

  // ── MOBILIER ─────────────────────────────────────────────────────
  {
    id:          'table-basse',
    name:        'Table Basse Moderne',
    nameAr:      'طاولة قهوة عصرية',
    category:    'mobilier',
    emoji:       '🪑',
    priceDA:     35_000,
    priceUnit:   'unité',
    dimensions:  '120 × 60 × 45 cm',
    description: 'Table basse plateau verre trempé 10mm sur pieds métal noir mat. Design épuré.',
    model3d:     '/models/coffee-table.glb',
    inStock:     true,
  },
  {
    id:          'canape-3pl',
    name:        'Canapé 3 Places Velours',
    nameAr:      'أريكة 3 أشخاص مخمل',
    category:    'mobilier',
    emoji:       '🛋️',
    priceDA:     120_000,
    priceUnit:   'unité',
    dimensions:  '220 × 90 × 85 cm',
    description: 'Canapé 3 places tissu velours. Coloris beige, gris ou vert sauge. Livraison et montage inclus.',
    model3d:     '/models/sofa.glb',
    inStock:     true,
  },


  // ────────────────────────────────────────────────────────────────
  // 🚪 SECTION — PORTES INVISIBLES EN WPC
  // Portes affleurantes intégrées dans le revêtement mural
  // ────────────────────────────────────────────────────────────────

  {
    id:          'porte-wpc-noyer',
    name:        'Porte Invisible WPC Noyer',
    nameAr:      'باب مخفي WPC بلوط',
    category:    'porte-wpc' as const,
    emoji:       '🚪',
    priceDA:     85_000,
    priceUnit:   'unité' as const,
    dimensions:  '210 × 90 cm · épaisseur 4 cm · sur mesure',
    description: 'Porte invisible affleurante intégrée dans le parement mural en WPC finition noyer. Charnières cachées, joint discret 2 mm. La porte disparaît dans le mur. Idéale pour dressing, buanderie, chambre.',
    image:       '/images/portes/porte-invisible-wpc-noyer.jpg',
    inStock:     true,
  },
  {
    id:          'porte-wpc-blanc-mat',
    name:        'Porte Invisible WPC Blanc Mat',
    nameAr:      'باب مخفي WPC أبيض مطفأ',
    category:    'porte-wpc' as const,
    emoji:       '🚪',
    priceDA:     78_000,
    priceUnit:   'unité' as const,
    dimensions:  '210 × 90 cm · sur mesure 60–100 cm',
    description: 'Porte invisible en WPC laqué blanc mat. S\'intègre parfaitement dans un mur blanc ou un parement shiplap. Montage à gauche ou droite. Livrée avec cadre affleurant et joints brossés.',
    inStock:     true,
  },
  {
    id:          'porte-wpc-anthracite',
    name:        'Porte Invisible WPC Anthracite',
    nameAr:      'باب مخفي WPC أنثراسيت',
    category:    'porte-wpc' as const,
    emoji:       '🚪',
    priceDA:     82_000,
    priceUnit:   'unité' as const,
    dimensions:  '210 × 90 cm · H personnalisable jusqu\'à 270 cm',
    description: 'Porte invisible WPC finition anthracite mat. Compatible avec revêtements muraux shiplap bois foncé ou panneaux MDF. Discrétion absolue, finition soignée. Fabrication sur mesure Oran.',
    inStock:     true,
  },
  {
    id:          'porte-wpc-double',
    name:        'Double Porte Invisible WPC',
    nameAr:      'باب مزدوج مخفي WPC',
    category:    'porte-wpc' as const,
    emoji:       '🚪',
    priceDA:     145_000,
    priceUnit:   'unité' as const,
    dimensions:  '210 × 160 cm (2×80) · sur mesure',
    description: 'Double porte invisible WPC pour grande ouverture salon. Deux battants synchronisés. Intégration totale dans le mur parement. Parfait pour séparation salon / couloir ou suite parentale.',
    image:       '/images/portes/porte-invisible-wpc-noyer.jpg',
    inStock:     true,
  },

  // ── Accessoires portes WPC ────────────────────────────────────────
  {
    id:          'charniere-invisible',
    name:        'Charnières Invisibles (paire)',
    nameAr:      'مفصلات مخفية',
    category:    'porte-wpc' as const,
    emoji:       '⚙️',
    priceDA:     4_500,
    priceUnit:   'unité' as const,
    dimensions:  'Charge max 80 kg · acier inox',
    description: 'Paire de charnières invisibles pour porte affleurante. Réglage 3D (haut/bas/profondeur). Acier inoxydable 304, anti-corrosion. Compatible avec toutes nos portes WPC.',
    inStock:     true,
  },
  {
    id:          'poussoir-magnetique',
    name:        'Poussoir Magnétique Discret',
    nameAr:      'دافع مغناطيسي',
    category:    'porte-wpc' as const,
    emoji:       '🔲',
    priceDA:     1_800,
    priceUnit:   'unité' as const,
    dimensions:  '50 × 20 mm · force 5 kg',
    description: 'Mécanisme push-to-open magnétique. Aucune poignée visible — appuyer pour ouvrir. Installation encastrée invisible. Idéal pour les portes invisibles sans poignée.',
    inStock:     true,
  },
  {
    id:          'cadre-affleurant-wpc',
    name:        'Cadre Affleurant WPC',
    nameAr:      'إطار مسطح WPC',
    category:    'porte-wpc' as const,
    emoji:       '🔧',
    priceDA:     6_200,
    priceUnit:   'unité' as const,
    dimensions:  'Sur mesure · ép. 40 mm',
    description: 'Cadre affleurant en WPC finition assortie à la porte. Élimine tout décalage entre la porte et le mur. Livré avec joints silicone et visserie inox. Pose en 2 heures.',
    inStock:     true,
  },
  {
    id:          'pose-porte-invisible',
    name:        'Pose Complète Porte Invisible',
    nameAr:      'تركيب كامل للباب المخفي',
    category:    'porte-wpc' as const,
    emoji:       '🔨',
    priceDA:     12_000,
    priceUnit:   'forfait' as const,
    dimensions:  'Déplacement + installation + réglages',
    description: 'Installation professionnelle de votre porte invisible WPC. Inclut : calage du cadre, pose des charnières réglables, ajustement des joints, test d\'ouverture, finition joints silicone. Déplacement sur Oran inclus.',
    inStock:     true,
  },

  // ────────────────────────────────────────────────────────────────
  // 🪵 SECTION — FAUX SHIPLAP (lambris WPC + bois lamelles)
  // Revêtements muraux à lames verticales / horizontales style shiplap
  // ────────────────────────────────────────────────────────────────

  {
    id:          'faux-shiplap-bois-lamelles',
    name:        'Faux Shiplap Bois Lamelles 3D',
    nameAr:      'لوحات خشبية ثلاثية الأبعاد',
    category:    'faux-shiplap' as const,
    emoji:       '🪵',
    priceDA:     3_800,
    priceUnit:   'm²' as const,
    dimensions:  'Lame 180 × 2.2 cm · ép. 18 mm · pas 4 cm',
    description: 'Revêtement mural shiplap à lames rondes en WPC effet bois naturel. Rainures profondes créant un effet 3D et ombres portées élégantes. Résistant humidité. Idéal pour mur TV, couloir, entrée, cuisine.',
    image:       '/images/portes/faux-shiplap-bois-lamelles.jpg',
    inStock:     true,
  },
  {
    id:          'faux-shiplap-chene-clair',
    name:        'Shiplap Chêne Clair Huilé',
    nameAr:      'ألواح بلوط فاتح مدهون',
    category:    'faux-shiplap' as const,
    emoji:       '🪵',
    priceDA:     3_200,
    priceUnit:   'm²' as const,
    dimensions:  'Lame 200 × 18 cm · ép. 12 mm · L personnalisable',
    description: 'Lambris shiplap horizontal en WPC finition chêne clair huilé. Teinte naturelle chaleureuse. Pose clipsée sans colle. Compatible avec LED indirect. Certifié résistant humidité — idéal salle de bain et cuisine.',
    image:       '/images/portes/faux-shiplap-bois-lamelles.jpg',
    inStock:     true,
  },
  {
    id:          'faux-shiplap-noyer-fonce',
    name:        'Shiplap Noyer Foncé Premium',
    nameAr:      'ألواح جوز داكن فاخر',
    category:    'faux-shiplap' as const,
    emoji:       '🌑',
    priceDA:     4_500,
    priceUnit:   'm²' as const,
    dimensions:  'Lame 200 × 18 cm · ép. 14 mm',
    description: 'Shiplap premium finition noyer foncé veinage naturel. Ambiance luxe et contemporaine. Compatible avec LED warm white pour effet cosy haut de gamme. Très prisé pour murs TV et chambres à Oran.',
    inStock:     true,
  },
  {
    id:          'faux-shiplap-blanc-artic',
    name:        'Shiplap Blanc Arctique Mat',
    nameAr:      'ألواح أبيض مطفأ',
    category:    'faux-shiplap' as const,
    emoji:       '⬜',
    priceDA:     2_900,
    priceUnit:   'm²' as const,
    dimensions:  'Lame 200 × 14 cm · ép. 10 mm',
    description: 'Lambris shiplap blanc arctique mat. Agrandit visuellement les petits espaces. Style scandinave épuré. Idéal pour couloir, chambre enfant, bureau. Peindre possible avec peinture acrylique.',
    inStock:     true,
  },
  {
    id:          'faux-shiplap-gris-beton',
    name:        'Shiplap Effet Béton Gris',
    nameAr:      'ألواح أثر الخرسانة رمادي',
    category:    'faux-shiplap' as const,
    emoji:       '🔲',
    priceDA:     3_600,
    priceUnit:   'm²' as const,
    dimensions:  'Lame 200 × 20 cm · ép. 12 mm',
    description: 'Shiplap finition béton ciré gris. Tendance industrielle urbaine. S\'associe parfaitement avec les meubles TV noirs et les LED warm. Résistant aux chocs et à l\'humidité. Grande largeur de lame effet architectural.',
    inStock:     true,
  },

  // ── Accessoires faux shiplap ──────────────────────────────────────
  {
    id:          'clips-pose-shiplap',
    name:        'Clips de Pose Shiplap (50 pcs)',
    nameAr:      'مشابك تركيب (50 قطعة)',
    category:    'faux-shiplap' as const,
    emoji:       '📎',
    priceDA:     1_200,
    priceUnit:   'unité' as const,
    dimensions:  '50 clips · acier galvanisé',
    description: 'Kit de 50 clips de fixation pour lames shiplap. Pose sans colle ni vis apparentes. Compatible avec toutes nos lames WPC. Espacement de 30 cm recommandé. Livré avec instructions de pose.',
    inStock:     true,
  },
  {
    id:          'rail-alu-shiplap',
    name:        'Rail Aluminium de Pose (3 m)',
    nameAr:      'قضيب ألومينيوم للتركيب',
    category:    'faux-shiplap' as const,
    emoji:       '📏',
    priceDA:     850,
    priceUnit:   'unité' as const,
    dimensions:  '3 m · alu anodisé · ép. 2 mm',
    description: 'Rail de départ et intermédiaire en aluminium anodisé pour pose shiplap sur mur. Garantit l\'aplomb et l\'espacement régulier. Indispensable pour une finition pro. 1 rail / 60 cm de hauteur recommandé.',
    inStock:     true,
  },
  {
    id:          'colle-construction-wpc',
    name:        'Colle Construction WPC (310 ml)',
    nameAr:      'غراء بناء WPC',
    category:    'faux-shiplap' as const,
    emoji:       '🧴',
    priceDA:     680,
    priceUnit:   'unité' as const,
    dimensions:  'Cartouche 310 ml · couvre 4 m²',
    description: 'Colle spéciale WPC et lambris muraux. Compatible carrelage, béton, placo, bois. Flexible après séchage. Résistant humidité classe D3. Séchage 24h. Idéale en complément des clips.',
    inStock:     true,
  },
  {
    id:          'baguette-angle-shiplap',
    name:        "Baguette d'Angle Finition (2 m)",
    nameAr:      'قضيب زاوية تشطيب',
    category:    'faux-shiplap' as const,
    emoji:       '📐',
    priceDA:     920,
    priceUnit:   'unité' as const,
    dimensions:  '2 m · inox brossé ou PVC assorti',
    description: 'Baguette d\'angle de finition pour les coins intérieurs et extérieurs du shiplap. Disponible en inox brossé (look luxe) ou PVC coloris assorti (discret). Garantit une finition impeccable aux angles.',
    inStock:     true,
  },
  {
    id:          'pose-shiplap-pro',
    name:        "Pose Shiplap & WPC au m²",
    nameAr:      'تركيب ألواح WPC بالمتر المربع',
    category:    'faux-shiplap' as const,
    emoji:       '🔧',
    priceDA:     1_400,
    priceUnit:   'm²' as const,
    dimensions:  'Main d\'œuvre + déplacement Oran',
    description: 'Pose professionnelle de vos lames shiplap ou WPC au mètre carré. Inclut : marquage horizontal, pose des rails, fixation clips, coupe sur mesure, finition angles, nettoyage. Délai 1–2 jours selon surface.',
    inStock:     true,
  },
  {
    id:          'forfait-shiplap-complet',
    name:        'Forfait Shiplap Complet (fourni + posé)',
    nameAr:      'باقة كاملة شيبلاب مع التركيب',
    category:    'faux-shiplap' as const,
    emoji:       '🏆',
    priceDA:     6_500,
    priceUnit:   'm²' as const,
    dimensions:  'Lames + accessoires + pose · clé en main',
    description: 'Forfait tout inclus : lames shiplap WPC finition au choix + rails aluminium + clips + colle + baguettes d\'angle + pose complète. Prix clé en main par m². Devis personnalisé selon votre surface et finition.',
    inStock:     true,
  },

  
  // ────────────────────────────────────────────────────────────────
  // PORTE SECRETE — integree dans le shiplap/wpc
  // ────────────────────────────────────────────────────────────────

  {
    id:          'porte-secrete-shiplap-gris',
    name:        'Porte Secrete Shiplap Gris Anthracite',
    nameAr:      'باب سري شيبلاب رمادي',
    category:    'porte-wpc' as const,
    emoji:       '👁️',
    priceDA:     95_000,
    priceUnit:   'unité' as const,
    dimensions:  '210 x 90 cm . parement shiplap integre . sur mesure',
    description: 'Porte secrete integree dans un mur shiplap gris anthracite. La porte est totalement invisible dans le revetement. Lames verticales continues. Finition discrete poussoir magnetique. Effet Service Discret haut de gamme.',
    image:       '/images/portes/porte-secrete-shiplap-gris.jpg',
    inStock:     true,
  },
  {
    id:          'porte-secrete-wpc-noyer',
    name:        'Porte Secrete WPC Noyer Mur Bois',
    nameAr:      'باب سري WPC جوز في جدار خشبي',
    category:    'porte-wpc' as const,
    emoji:       '🚪',
    priceDA:     105_000,
    priceUnit:   'unité' as const,
    dimensions:  '210 x 90 cm . integration totale . sur mesure',
    description: 'Porte secrete dans un mur revetu WPC noyer. Lames verticales continues sur toute la hauteur. Charnieres piano dissimulees. Pour dressing, suite parentale, bureau prive.',
    image:       '/images/portes/porte-invisible-wpc-noyer.jpg',
    inStock:     true,
  },

  // ────────────────────────────────────────────────────────────────
  // LED RGB ACOUSTIQUE — arriere TV + deco murale
  // ────────────────────────────────────────────────────────────────

  {
    id:          'led-rgb-acoustique-tv',
    name:        'LED RGB Acoustique Arriere TV 3m',
    nameAr:      'LED RGB صوتية خلف التلفزيون',
    category:    'lumiere' as const,
    emoji:       '🎵',
    priceDA:     8_500,
    priceUnit:   'unité' as const,
    dimensions:  '3 m . USB + telecommande + application WiFi',
    description: 'Ruban LED RGB reactif au son (mode acoustique). Se synchronise avec la musique et les effets sonores de la TV. Retroeclairage cinema derriere la TV. 16 millions de couleurs, mode musical, mode statique, minuterie. App Android iOS.',
    inStock:     true,
  },
  {
    id:          'led-rgb-acoustique-5m',
    name:        'LED RGB Acoustique 5m Premium',
    nameAr:      'LED RGB صوتية 5 متر فاخر',
    category:    'lumiere' as const,
    emoji:       '🌈',
    priceDA:     13_500,
    priceUnit:   'unité' as const,
    dimensions:  '5 m . ruban 24V . IP44 . etanche semi',
    description: 'Ruban LED RGB 5 m haute densite reactif au son. Ideal pour encadrement mural TV + plafond indirect. Bande large 15 mm, 60 LEDs par m. Boitier amplificateur audio integre. Compatible Alexa Google Home.',
    inStock:     true,
  },
  {
    id:          'led-neon-flex-or',
    name:        'LED Neon Flex Dore Ambiance 2m',
    nameAr:      'LED نيون فليكس ذهبي',
    category:    'lumiere' as const,
    emoji:       '✨',
    priceDA:     9_800,
    priceUnit:   'unité' as const,
    dimensions:  '2 m . silicone souple . 3000K warm . IP65',
    description: 'Tube LED neon flexible warm white dore 3000K. Courbe et forme libre. Ideal pour creer une ambiance doree derriere le meuble TV ou sur un mur shiplap. Discret, resistant, alimentation 12V incluse.',
    inStock:     true,
  },
  {
    id:          'led-bande-indirect-plafond',
    name:        'LED Indirect Faux Plafond 5m',
    nameAr:      'LED غير مباشر سقف كاذب',
    category:    'lumiere' as const,
    emoji:       '💫',
    priceDA:     7_200,
    priceUnit:   'unité' as const,
    dimensions:  '5 m . 12V . warm 3000K . 600 LEDs',
    description: 'Ruban LED pour eclairage indirect faux plafond BA13. Lumiere douce et diffuse. Ideal pour corniche lumineuse salon, couloir, chambre. Haute densite 120 LEDs par m, rendu uniforme sans point lumineux visible.',
    inStock:     true,
  },
  {
    id:          'controleur-led-wifi-musique',
    name:        'Controleur LED WiFi Musique',
    nameAr:      'وحدة تحكم LED واي فاي موسيقى',
    category:    'lumiere' as const,
    emoji:       '🎛️',
    priceDA:     3_200,
    priceUnit:   'unité' as const,
    dimensions:  'Boitier 85x45mm . 12/24V . 20A max',
    description: 'Controleur WiFi RGB avec microphone integre pour mode reactif musique. Compatible avec tous nos rubans LED RGB. Application Magic Home Android iOS. Programmation horaire, scenes, synchronisation multi-zones.',
    inStock:     true,
  },
  {
    id:          'alimentation-led-100w',
    name:        'Alimentation LED 12V 100W',
    nameAr:      'محول كهربائي LED 12 فولت',
    category:    'lumiere' as const,
    emoji:       '🔌',
    priceDA:     2_400,
    priceUnit:   'unité' as const,
    dimensions:  '195x45x35mm . IP20 . certifie CE',
    description: 'Transformateur LED 12V 100W pour rubans LED interieurs. Sortie stable, protege contre les courts-circuits et la surchauffe. Ideal pour alimenter 5 a 8 metres de LED haute densite. Silencieux, faible consommation veille.',
    inStock:     true,
  },

  // ── SERVICES ─────────────────────────────────────────────────────
  {
    id:          'pose-mur',
    name:        'Pose Revêtement Mural',
    nameAr:      'تركيب تغطية الجدران',
    category:    'services',
    emoji:       '🔧',
    priceDA:     800,
    priceUnit:   'm²',
    dimensions:  "Main d'œuvre incluse",
    description: 'Pose de tout revêtement mural (marbre, shiplap, BA13, panneau 3D). Déplacement Oran inclus.',
    inStock:     true,
  },
  {
    id:          'pose-meuble',
    name:        'Installation Meuble TV',
    nameAr:      'تركيب طاولة التلفزيون',
    category:    'services',
    emoji:       '🪛',
    priceDA:     5_000,
    priceUnit:   'forfait',
    dimensions:  'Déplacement + montage',
    description: 'Montage et installation complète de votre meuble TV. Câbles dissimulés, fixation murale si besoin.',
    inStock:     true,
  },
]

// ── Utilitaires ────────────────────────────────────────────────────
export const getProductsByCategory = (cat: string) =>
  PRODUCTS.filter(p => p.category === cat)

export const getProductById = (id: string) =>
  PRODUCTS.find(p => p.id === id) ?? null

export const CATEGORIES = [
  { id: 'tv-simple',    label: 'Meubles TV',        emoji: '📺', section: 'tv'       },
  { id: 'tv-deco',      label: 'TV + Placo Déco',   emoji: '🏛️', section: 'tv'       },
  { id: 'tv',           label: 'TV Classiques',     emoji: '🖥️', section: 'tv'       },
  { id: 'porte-wpc',    label: 'Portes Invisibles', emoji: '🚪', section: 'portes'   },
  { id: 'faux-shiplap', label: 'Faux Shiplap',      emoji: '🪵', section: 'portes'   },
  { id: 'murs',         label: 'Revêtements',       emoji: '🪨', section: 'autres'   },
  { id: 'lumiere',      label: 'Éclairage',         emoji: '💡', section: 'autres'   },
  { id: 'mobilier',     label: 'Mobilier',          emoji: '🛋️', section: 'autres'   },
  { id: 'services',     label: 'Services',          emoji: '🔧', section: 'autres'   },
] as const

export const formatPrice = (da: number) =>
  new Intl.NumberFormat('fr-DZ', { style: 'decimal' }).format(da) + ' DA'
